<a href="https://colab.research.google.com/github/Binitaaaaaa/numpy/blob/main/lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 1-D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("1-D Array:")
print(array_1d)

# Create a 2-D array
array_2d = np.array([[7, 8, 9], [10, 11, 12]])
print("\n2-D Array:")
print(array_2d)

# Convert 1-D array to 2-D using reshape()
array_1d_to_2d = array_1d.reshape(2, 3)  # Reshape to 2 rows and 3 columns
print("\nReshaped 1-D to 2-D Array:")
print(array_1d_to_2d)

# Add two arrays
array_sum = array_1d_to_2d + array_2d
print("\nSum of Arrays:")
print(array_sum)

# Find the shape of a 2-D array
shape_of_2d = array_2d.shape
print("\nShape of 2-D Array:")
print(shape_of_2d)


1-D Array:
[1 2 3 4 5 6]

2-D Array:
[[ 7  8  9]
 [10 11 12]]

Reshaped 1-D to 2-D Array:
[[1 2 3]
 [4 5 6]]

Sum of Arrays:
[[ 8 10 12]
 [14 16 18]]

Shape of 2-D Array:
(2, 3)


In [2]:
import numpy as np

# Create a 2-D array
array_2d = np.array([[7, 8, 9], [10, 11, 12]])

# Access the last data of the 2-D array
last_element = array_2d[-1, -1]  # Use negative indexing: -1 for the last row, -1 for the last column

print("2-D Array:")
print(array_2d)

print("\nLast Element of the 2-D Array:")
print(last_element)


2-D Array:
[[ 7  8  9]
 [10 11 12]]

Last Element of the 2-D Array:
12


In [3]:
import numpy as np

# Create a 1-D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("1-D Array:")
print(array_1d)

# Slice the 1-D array
slice_1d = array_1d[1:4]  # Extract elements from index 1 to 3 (4 is exclusive)
print("\nSliced 1-D Array (index 1 to 3):")
print(slice_1d)

# Negative slicing on 1-D array
negative_slice_1d = array_1d[-3:]  # Extract the last three elements
print("\nNegative Sliced 1-D Array (last 3 elements):")
print(negative_slice_1d)

# Create a 2-D array
array_2d = np.array([[7, 8, 9], [10, 11, 12]])
print("\n2-D Array:")
print(array_2d)

# Slice the 2-D array
slice_2d = array_2d[:, 1:3]  # Extract columns 1 and 2 for all rows
print("\nSliced 2-D Array (columns 1 and 2):")
print(slice_2d)

# Negative slicing on 2-D array
negative_slice_2d = array_2d[-1, -2:]  # Extract the last row and last two elements
print("\nNegative Sliced 2-D Array (last row, last 2 elements):")
print(negative_slice_2d)


1-D Array:
[1 2 3 4 5 6]

Sliced 1-D Array (index 1 to 3):
[2 3 4]

Negative Sliced 1-D Array (last 3 elements):
[4 5 6]

2-D Array:
[[ 7  8  9]
 [10 11 12]]

Sliced 2-D Array (columns 1 and 2):
[[ 8  9]
 [11 12]]

Negative Sliced 2-D Array (last row, last 2 elements):
[11 12]


In [4]:
import numpy as np

# Create a 1-D array
array_1d = np.array([1, 3, 5, 7, 9, 11])
print("1-D Array:")
print(array_1d)

# Use where() to find indices of elements that satisfy a condition
indices_where = np.where(array_1d > 5)  # Find indices of elements greater than 5
print("\nIndices where elements are greater than 5:")
print(indices_where)
print("Elements greater than 5:")
print(array_1d[indices_where])

# Use searchsorted() to find the insertion index for a value
sorted_index = np.searchsorted(array_1d, 6)  # Find where 6 would fit in the sorted array
print("\nIndex where 6 can be inserted to maintain sorted order:")
print(sorted_index)

# Create a 2-D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\n2-D Array:")
print(array_2d)

# Use where() to find indices in a 2-D array
indices_2d_where = np.where(array_2d > 50)  # Find where elements are greater than 50
print("\nIndices where elements are greater than 50 (row, column):")
print(indices_2d_where)
print("Elements greater than 50:")
print(array_2d[indices_2d_where])


1-D Array:
[ 1  3  5  7  9 11]

Indices where elements are greater than 5:
(array([3, 4, 5]),)
Elements greater than 5:
[ 7  9 11]

Index where 6 can be inserted to maintain sorted order:
3

2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Indices where elements are greater than 50 (row, column):
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Elements greater than 50:
[60 70 80 90]


In [7]:
import numpy as np
from scipy import stats

# Create a 1-D array
data = np.array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])
print("1-D Data:")
print(data)

# Calculate mean
mean = np.mean(data)
print("\nMean:")
print(mean)

# Calculate median
median = np.median(data)
print("\nMedian:")
print(median)

# Calculate mode
mode_result = stats.mode(data, keepdims=True)  # Explicitly keep the dimension if needed
mode_value = mode_result.mode.item()           # Extract scalar mode value
mode_count = mode_result.count.item()          # Extract scalar count value
print("\nMode:")
print(mode_value)  # Mode value
print("Mode count:", mode_count)  # Frequency of the mode

# Calculate standard deviation
std_dev = np.std(data)
print("\nStandard Deviation:")
print(std_dev)

# Calculate variance
variance = np.var(data)
print("\nVariance:")
print(variance)

# Calculate Mean Squared Error (MSE)
true_values = np.array([2, 3, 4, 5, 6, 6, 7, 8, 9, 10])  # Example true values
mse = np.mean((data - true_values) ** 2)
print("\nMean Squared Error (MSE):")
print(mse)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("\nRoot Mean Squared Error (RMSE):")
print(rmse)


1-D Data:
[1 2 3 4 5 5 6 7 8 9]

Mean:
5.0

Median:
5.0

Mode:
5
Mode count: 2

Standard Deviation:
2.449489742783178

Variance:
6.0

Mean Squared Error (MSE):
1.0

Root Mean Squared Error (RMSE):
1.0


In [8]:
import pandas as pd
import numpy as np

# Create NumPy arrays for data
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
ages = np.array([25, 30, 35, 40])
salaries = np.array([50000, 60000, 70000, 80000])

# Create a dictionary where keys are column names and values are NumPy arrays
data = {
    'Name': names,
    'Age': ages,
    'Salary': salaries
}

# Create a DataFrame using the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame created using dictionaries and NumPy arrays:")
print(df)


DataFrame created using dictionaries and NumPy arrays:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
